### ISSUE TITLE
simple point marker causes empty file:// 

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/bridge-style#15]
the simple point style: [empty-wkn-file.qgz.zip](https://github.com/GeoCat/bridge-style/files/3659953/empty-wkn-file.qgz.zip)
![image](https://user-images.githubusercontent.com/299829/65725586-56b54980-e0b3-11e9-8c37-e71e34475b31.png)
causes emtpy file:// in geostyler:
```
 {


                    "opacity": 1.0,
                    "rotate": 0.0,
                    "color": "#afe77a",
                    "kind": "Mark",
                    "wellKnownName": "file://",
                    "size": 1.88976377955,
                    "strokeColor": "#000000",
                    "strokeWidth": 1
                }
```

(this throws a file-not-found in qgis-bridge)

**Comment by pvgenuchten** [comment]
mmm, indeed above project only has circle, not sure which project i used, a similar effect is in this project, the wellknownname is not file://, but it has things as file://arial and file://circle, which seems not correct

[point-file-mark.qgz.zip](https://github.com/GeoCat/bridge-style/files/3678694/point-file-mark.qgz.zip)

**Comment by volaya** [comment]
This should be fixed. Please re-test
