### ISSUE TITLE
adding an offset to a point marker makes it disappear in geoserver

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/bridge-style#17]
Seems the SLD writer adds this to manage the offset:

```
<PointSymbolizer>
            <Geometry>
              <ogc:Function name="offset">
                <ogc:PropertyName>geom</ogc:PropertyName>
                <ogc:Sub>
                  <ogc:Literal>0</ogc:Literal>
                  <ogc:Literal>5.0</ogc:Literal>
                </ogc:Sub>
                <ogc:Sub>
                  <ogc:Literal>0</ogc:Literal>
                  <ogc:Literal>5.0</ogc:Literal>
                </ogc:Sub>
              </ogc:Function>
            </Geometry>
            <Graphic>
```
for me it makes the marker disappear at all in geoserver 2.16

[offset.qgz.zip](https://github.com/GeoCat/bridge-style/files/3660085/offset.qgz.zip)

**Comment by pvgenuchten** [comment]
ah, the geometry offset function works actually ok, but it works in real world units (not map units) if you change the displacement to 0.001 the offset is still close to the marker, but with values like 2 or 5 it moves out of the visible area quite soon. also the offset seems to have an opposite Y direction then qgis 1,1 in qgis would be 0.01,-0.01 in geoserver...

**Comment by pvgenuchten** [comment]
@jodygarnett is there an alternative solution in geoserver that uses screen pix for offset?

**Comment by jodygarnett** [comment]
Yes, offsets/anchors/displacements are baked into the SZE specification and work in pixels (or units of your choice):

* line symbolizer has offset
* polygon symbolizer has offset and displacement
* point symbolizer has anchor and displacement

Reference:

* [YSLD Point Symbolizer](https://docs.geoserver.org/stable/en/user/styling/ysld/reference/symbolizers/point.html)
* [YSLD Point Workshop](https://docs.geoserver.org/latest/en/user/styling/workshop/ysld/point.html)

**Comment by pvgenuchten** [comment]
Please use 

```xml
<Displacement>
<DisplacementX>3</DisplacementX><DisplacementY>2</DisplacementY>
</Displacement>
```

 in stead of the geometry displacement function

**Comment by jodygarnett** [comment]
sigh - perhaps that is just for text symbolizers:

* anchor provides two values expressing how a label is aligned with respect to the starting label position.
* displacement is be used to provide an initial displacement using and x and y offset. For points this offset is recommended to adjust the label position away for the area used by the symbol.

If we need to use the geometry offset function you can perform the same calculations used by displacement. We should be sure to test on a high def display also (an environmental variable is provided but I cannot remember if we need to make use of it or not).

```xml
            <Geometry>
              <ogc:Function name="offset">
                <ogc:PropertyName>geom</ogc:PropertyName>
                <ogc:Function name="rescaleToPixels">
                  <ogc:Literal>-5</ogc:Literal>
                  <ogc:Literal>pixel</ogc:Literal>
                  <ogc:Div>
                     <Literal>1.0</Literal>
                     <Function name="env><Literal> wms_scale_denominator</Literal></Function>
                  </ogc:Div>
                  <ogc:Literal>0</ogc:Literal>
                </ogc: Function>
                <ogc:Function name="rescaleToPixels">
                  <ogc:Literal>-5</ogc:Literal>
                  <ogc:Literal>pixel</ogc:Literal>
                  <ogc:Div>
                     <Literal>1.0</Literal>
                     <Function name="env><Literal> wms_scale_denominator</Literal></Function>
                  </ogc:Div>
                  <ogc:Literal>0</ogc:Literal>
                </ogc: Function>
              </ogc:Function>
            </Geometry>
            <Graphic>
```

**Comment by pvgenuchten** [comment]
I tested the displacement property in geoserver and it resulted in the expected behavior, good to know about the rescaletopixels option, this would also solve the case...

**Comment by volaya** [comment]
Explanation for this: I was lazy and thought that, instead of using the offset, I could just do a geometry transform. That way, when later implementing the conviersion to any new format. I would just have to deal with the geom transform. Turns out it was not a good idea. Will rewrite that and use the supported offset values

**Comment by arashmad** [comment]
I'm working on an extension that generate `.sld` files from **ESRI** `.mxd` (map document). I realized that **offset function** effects only geometry. But how can I displace character when we have `Character Marker` in point symbolizer.
This is what I'm addressing is as follow:
`
<PointSymbolizer>
<Graphic>
	<Mark>
		<WellKnownName>ttf://c://windows//fonts//esri_11.ttf#41</WellKnownName>
		<Fill><CssParameter name="fill">#000000</CssParameter></Fill>
	</Mark>
	<Size>15.96</Size>
</Graphic>
</PointSymbolizer>
<PointSymbolizer>
	<Graphic>
		<Mark>
			<WellKnownName>ttf://C://Windows//Fonts//esri_33.ttf#70</WellKnownName>
			<Fill><CssParameter name="fill">#000000</CssParameter></Fill>
		</Mark>
		<Size>10.64</Size>
	</Graphic>
</PointSymbolizer>
`
