### ISSUE TITLE
"None is not defined"

### ISSUE THREAD

**Issue by tomchadwin** [GeoCat/bridge-style#2]
I am exporting a line layer from QGIS to Mapbox. I simply a shapefile in QGIS, and made no change to the randomly assigned simple style. The conversion results in this:

```
'line-offset': None
```

We need to convert `None` to something compatible, which will depend on the property, I guess (in this case `0`). Or we need to test that properties have a value before writing them out.

**Comment by jodygarnett** [comment]
In this case we could also note that 0 is the default and write nothing out.
