### ISSUE TITLE
Use within QGIS plugin fails

### ISSUE THREAD

**Issue by tomchadwin** [GeoCat/bridge-style#23]
I'm not 100% sure, but I think using bridgestyle within a QGIS plugin fails because of a naming clash with `qgis`. I get around this in eg /bridgestyle/qgis/\_\_init__.py by changing:

```python
from bridgestyle import qgis
[snip]
geostyler, icons, warnings = qgis.togeostyler.convert(layer)
```

to:

```python
from bridgestyle.qgis import togeostyler
[snip]
geostyler, icons, warnings = togeostyler.convert(layer)
```

Is there a way around this?

**Comment by volaya** [comment]
Yes, there is a name clash, and we actually use it within the geocatbridge plugin in the second way that you mention. Is that really a big problem to make imports that way? Any suggestion?

**Comment by volaya** [comment]
I would suggest using a git submodule for now, since the library is still indevelopment

That way you use the most current code, and that should not be a problem (as long as other plugins that use it have the same version)

**Comment by tomchadwin** [comment]
I'll try - I couldn't get a submodule to work with Travis when I tried with https://github.com/NathanW2/qgs2js. Thanks.

**Comment by volaya** [comment]
There is actually no naming clash. Just missing imports. Should be fixed in here

https://github.com/GeoCat/bridge-style/commit/a8db891a322346520d0ad93f5c87dede96b58f88

You should be able to now use `from bridgestyle import qgis` and then call `qgis.togeostyler`

**Comment by tomchadwin** [comment]
Tested and confirmed as fixed. Thanks very much!
