### ISSUE TITLE
Angle None causes error in mapserver

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/bridge-style#26]
When angle equals None, do not add the angle property
on point layer in mapserver

**Comment by volaya** [comment]
Can you provide an example qgis style? I dont see how angle can end up having that value when geostyler is created from qgis

**Comment by pvgenuchten** [comment]
this layer causes the angle:None
[point-no-angle.qgz.zip](https://github.com/GeoCat/bridge-style/files/3725522/point-no-angle.qgz.zip)
