### ISSUE TITLE
expression in classification has bad syntax

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/bridge-style#28]
string values seem not quoted in expressions

```
msEvalExpression: Expression parser error. Failed to parse expression: [THEMA] = gld
yyparse(): Expression parser error. syntax error
```

![image](https://user-images.githubusercontent.com/299829/66758748-35b86b00-ee9f-11e9-98f0-7582b59d06f5.png)

**Comment by volaya** [comment]
Already fixed
