### ISSUE TITLE
opacity gives blank image in mapserver 7.2

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/bridge-style#29]
[docs](https://mapserver.org/mapfile/style.html#style) state that opacity is supported, however on a line layer:

```
OPACITY 1.0
```

made the layer disappear

**Comment by geographika** [comment]
@pvgenuchten - values here are 0-100 with 0 being fully transparent. I guess a value of 1 is close enough to invisible to make it disappear?

**Comment by pvgenuchten** [comment]
ah, let me try that

confirmed, so val*100...
