### ISSUE TITLE
expression syntax mapserver

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/bridge-style#30]
expressions are a bit typical in mapserver

you either use 

```
classitem {fieldname}
class {value}
```

or use 

```
expression [fieldname] eq {value}
```

in case of string comparison make sure to quote both the field as well as the value

```
expression "[name]" eq "Victor"
```

https://mapserver.org/mapfile/expressions.html#expressions

**Comment by geographika** [comment]
@pvgenuchten - I ran into issues/misunderstandings with expressions this weekend. There is a new set of tests for more complex MapServer expressions at https://github.com/mapserver/mapserver/pull/5897 that may be of use.

**Comment by volaya** [comment]
I will add quoting to the fields name. We are not using the class or classitem elements
