### ISSUE TITLE
Feature request: blend modes

### ISSUE THREAD

**Issue by tomchadwin** [GeoCat/bridge-style#35]
Again, I don't know if blend modes are supported in geostyler, but they would be immensely valuable.

**Comment by pvgenuchten** [comment]
Tom, could you share a qgis project with some of these blend modes, extending geostyler is not a problem

**Comment by tomchadwin** [comment]
Sure:

https://tom.chadw.in/uploaded/QGIS_blend_modes.zip

Very simple examples included - one project with a blend mode applied at the layer level, and one a the symbol level. Let me know what other examples would be helpful.

**Comment by volaya** [comment]
Added here:

https://github.com/GeoCat/bridge-style/commit/7d52a424dd23d1c13dba5b7bfc7a5f4b54b344fa

That is for converting from qgis into geostyler and from there to sld. If you want, you can take it from there and add the geostyler -> mapbox conversion and make a PR. If not, let me know and I will take care of it when i have some time

**Comment by tomchadwin** [comment]
Wow! I'll take a look. Thanks so much!

**Comment by tomchadwin** [comment]
I must apologize wholeheartedly. It seems that belnd modes are not supported within MBGLJS. I misinterpreted a demo I saw in which the entire MBGLJS DOM element was blended, not layers within the map (https://twitter.com/BNiene/status/1161293078801633286).

I hope this proves useful in the other export formats, but it seems that Mapbox GL JS is a dead-end here.
