### ISSUE TITLE
QGIS "else" category/rule in Mapbox

### ISSUE THREAD

**Issue by tomchadwin** [GeoCat/bridge-style#5]
Since categories/ranges are converted to filters, is the QGIS `else` category converted? I'm not quite sure how it can work.

**Comment by tomchadwin** [comment]
I think ideally the treatment of QGIS complex renderers needs to change. At the moment, Each category/range/rule is exported as its own MBGLJS layer, with a `filter` mirroring the renderer rule expression. My gut feeling is that this presents three issues (of varying importance):

1. It might not be the most efficient way to style the MB map, and hence performance could perhaps be improved (I have no proof of this)
2. It makes handling an `else` rule difficult, if not impossible
3. It doesn't reflect the structure of the QGIS map (one QGIS layer with conditional styles becoming many MBGLJS conditional layers with one style)

I'm therefore starting to have a look to see whether we can take the returned filters and symbolisers, and instead of making them into layers with filters, make them into `paint`/`layout` `case` statements.

The fundamental issue with this is complexity, since we have to repeat the `case` statement for every style property. However, it still feels like the right way to do it.

I'm still familiarising myself with the codebase, and I don't kniow how successful I'll be in building such a prototype change. I'll do a PR for comparison only if I succeed, as I don't know whether such a change would be of interest.

**Comment by tomchadwin** [comment]
I've handled this at the implementation level, rather than within the library. I've restructured as described above. I'll therefore close this issue, though I still think it's worth consideration.

**Comment by pvgenuchten** [comment]
qgis else filter is converted (in sld it was recently added, not sure about mapboxgl)

**Comment by geraldo** [comment]
There is no ELSE like filter in Mapbox/Maplibre and filters like `"filter": "ELSE"` right now do through an error `filter: array expected, string found`

So the _convertExpression_ function in _mapboxgl/fromgeostyler.py_ actually should check not to return a `"ELSE"` string for filter, but `None`.
