### ISSUE TITLE
No labeling for Mapbox/Maplibre in Style Viewer

### ISSUE THREAD

**Issue by geraldo** [GeoCat/bridge-style#67]
I can't make _Single labels_ nor _Rule-based labeling_ mode make work for Mapbox/Maplibre, **Style Viewer** doesn't show any _symbol style layers_ using [text-font](https://maplibre.org/maplibre-style-spec/layers/#layout-symbol-text-font) property [as expected](https://geocat.github.io/qgis-bridge-plugin/v4.4/supported_symbology.html#labeling).

**Comment by geraldo** [comment]
I found the switch in [mapboxgl.fromgeostyler.py](https://github.com/GeoCat/bridge-style/blob/master/bridgestyle/mapboxgl/fromgeostyler.py#L16) and everything works fine when turning `_processTextSymbolizer = True`

I'm curious so why text processing is turned off for Mapbox/Maplibre, that's why I keep this issue open.

**Comment by GeoSander** [comment]
Hi @geraldo,

I honestly have no idea why this switch was introduced. It may just have been added in there (3 years ago, judging by `git blame`) for testing purposes. Or perhaps the idea was to make that option configurable for some reason.

No one has ever complained about it, so it's either never used or no one cared. Glad that you did!

I'd be happy to remove the switch altogether. There doesn't seem to be a clear reason to keep it in or make it configurable in my opinion. You can also make a PR if you want and I'll merge it. Might take a while before it appears in Bridge though.

Thanks,
Sander
