### ISSUE TITLE
Simple marker fails for Mapbox/Maplibre in Style Viewer

### ISSUE THREAD

**Issue by geraldo** [GeoCat/bridge-style#72]
Simple markers don't get converted to Mapbox/Maplibre and instead do show the following warning:

`Failed to convert to MapBox GL: unsupported operand type(s) for /: 'str' and 'float'`

Having a look at [mapboxgl/fromgeostyler.py](https://github.com/GeoCat/bridge-style/blob/master/bridgestyle/mapboxgl/fromgeostyler.py#L387) I see that the code for some reason is commented...

**Comment by geraldo** [comment]
Hi @GeoSander, the [new code](https://github.com/geraldo/bridge-style/commit/730ea294988deff805e02568a1f09abbb9a33f80) isn't committed. I had to reverse mine and something went wrong with the PR. How should we proceed? Maybe revert the last commit and I do a new PR based on your codebase?

**Comment by GeoSander** [comment]
Hi @geraldo, I am not sure what happened here.. I only commented on your PR, but afaik I haven't merged or reverted anything.
Either way, I did a hard reset to a3da0df3 and force-pushed to master to keep it clean, so you can do a new PR.

**Comment by geraldo** [comment]
ok @GeoSander , let's try again with the new PR

**Comment by geraldo** [comment]
Just figured out that there is an error in the last commit: [circle-radius](https://maplibre.org/maplibre-style-spec/layers/#paint-circle-circle-radius), etc. are _paint_ and not _layout_ properties. Will commit a PR asap.
