### ISSUE TITLE
QGIS Scale Depenent Visiblity of labels is ignored

### ISSUE THREAD

**Issue by geraldo** [GeoCat/bridge-style#82]
Right now QGIS _Scale Depenent Visiblity_ for labels is ignored when exported to GeoStyler. _qgis/togeostyler.py_ has the following code to have in mind scale-based visibility of labels, but doesn't work:
```
    if hasattr(labeling, 'dependsOnScale') and labeling.dependsOnScale():
        scale = processRuleScale(labeling)
        result["scaleDenominator"] = scale
```

I think the code instead should be the following:
```
    if (layer.hasScaleBasedVisibility()):
        scale = processRuleScale(layer)
        result["scaleDenominator"] = scale
```

Additionally labels renderer also can have a scale-based visibility, which should be used with the following code:
```
    if labeling is not None:
        settings = layer.labeling().settings()
        sv = settings.scaleVisibility
        if sv:
            scale = {"max": settings.minimumScale, "min": settings.maximumScale}
            result["scaleDenominator"] = scale
```

**Comment by geraldo** [comment]
I'm going to reopen this as there is a bug for _Scale Depenent Visiblity_ as a labels option. (It does work fine so for _Scale Depenent Visiblity_ as set in Layer Rendering.)

What happens is that in opposite to minimumScale and maximumScale in [Layers](https://qgis.org/pyqgis/master/core/QgsMapLayer.html#qgis.core.QgsMapLayer.minimumScale), it is a Property and not a Method in [QgsPalLayerSettings](https://qgis.org/pyqgis/master/core/QgsPalLayerSettings.html#qgis.core.QgsPalLayerSettings.minimumScale).

Now I also do remember why my test cases sometimes fail: It's when I do forget to restart QGIS after applying changes to bridgestyle library and just do use the Plugin Reloader. As documented [here](https://github.com/borysiasty/plugin_reloader/issues/37), actually Plugin Reloader doesn't reload loaded libraries. Sorry for that!

**Comment by GeoSander** [comment]
You are very consistent writing "Scale Dependent Visibility" as "Scale Depenent Visiblity" I have to say 😄 

Yes, the QGIS API is very consistent (not 🙄)... Good that you discovered it.
Will check and merge. Unfortunately this did not make the QGIS Bridge release, but it will be in a next one.
