### ISSUE TITLE
Add missing QGIS Line Stroke styles

### ISSUE THREAD

**Issue by geraldo** [GeoCat/bridge-style#88]
Actually only "Solid Line" Stroke Style for Line Symbols is implemented, but there do exist different options for dashed and dotted lines:

![image](https://github.com/GeoCat/bridge-style/assets/336371/a73ea09d-c360-44a5-9358-8bd8e611cf03)

I'm going to sumit a PR to add Stroke Styles for missing `Dash Line`, `Dot Line`, `Dash Dot Line` and `Dash Dot Dot Line`

**Comment by GeoSander** [comment]
I am a bit amazed that this has never been implemented @geraldo.
At first glance, it seems that it sets a default dash array when the line style is not "solid":
https://github.com/GeoCat/bridge-style/blob/00cff0ff89166c7f8af6542914d974dd81b9ae88/bridgestyle/qgis/togeostyler.py#L664-L665

Guess that it would be nice if the dash array will be properly set to whatever the pattern is. 👍

**Comment by geraldo** [comment]
Ok, for now I added the defined line styles as described in the issue. So it would be nice to also _Use custom dash pattern_ like:

![image](https://github.com/GeoCat/bridge-style/assets/336371/48119497-41b1-4351-a26b-60742946dda6)
