### ISSUE TITLE
Maplibre labels always on top

### ISSUE THREAD

**Issue by geraldo** [GeoCat/bridge-style#92]
QGIS draws labels always in top of feature symbology, for example in top of a line. Maplibre style draws layers in the same order as they are defined in the layers array. But this order right now seems to be a bit random instead of always put them in the end of the array, as expected.

Related to that, there is a "Z" parameter in the Maplibre style output, which doesn't exist in the Mapbox Style Specification. Any disadvantage of removing it?

**Comment by geraldo** [comment]
So what I would propose to do, is to reorder the rules layers after the first ordering at line 89 at [mapbox/fromgeostyler.py](https://github.com/GeoCat/bridge-style/blob/master/bridgestyle/mapboxgl/fromgeostyler.py#L89) using:

`layers.sort(key=lambda l: l["type"]=="symbol")`

@GeoSander, do you think this could have any negative side effects? For my case this works now, but I'm not sure if there could be a problem with markers...

**Comment by GeoSander** [comment]
Hi @geraldo, I'm not sure really, as I'm not very familiar with MapLibre/MapBox (I never touched any of the code related to that before).
What kind of problem with markers are you thinking of?
