### ISSUE TITLE
String concatenation expression transformed into math additions

### ISSUE THREAD

**Issue by aaime** [GeoCat/bridge-style#93]
**Describe the bug**
When using string concantenation to generate a label from multiple fields in QGIS, it's possible to use the "+" operator.
Exporting it, the generated OGC Filter expression is a `ogc:Add` rather than a `Concatenate` function.

**To Reproduce**

The following screenshot shows the input, the generated map, and the generated SLD:

![image](https://github.com/GeoCat/qgis-bridge-plugin/assets/325433/c8057c85-db68-4d8e-b3ee-2bd250a9dcbb)

**Expected behavior**
The plugin should recognize the different context and generate a string concatenation expression.

**Environment info (please complete the following information):**
 - OS: Widnows
 - QGIS version: 3.23
 - Bridge version: 4.4.1
 - Python version: whatever is coming with the QGIS installer

**Comment by GeoSander** [comment]
Good catch @aaime, this should definitely be fixed especially for labelling scenarios (which I believe is how you discovered this in the first place).

Since the style conversion actually happens in `bridge-style` and not in `qgis-bridge-plugin`, I took the liberty to transfer your issue.

**Comment by GeoSander** [comment]
Fixed and released as part of [GeoCat Bridge 4.5.0](https://plugins.qgis.org/plugins/geocatbridge/version/4.5.0/) for QGIS.
