### ISSUE TITLE
SLD file does not support when the raster style is set to Interpolation Discrete

### ISSUE THREAD

**Issue by dvandeijl** [GeoCat/bridge-style#98]
Describe the bug
When publishing a raster layer to GeoServer using GeoCat Bridge for QGIS 4.4.2 (based on bridgestyle 0.1.1), the SLD file does not support <ColorMap type="intervals"> when the raster style is set to "Interpolation: Discrete." Instead, the SLD file incorrectly includes <ColorMap type="ramp"> when it should include <ColorMap type="intervals">. This issue can be observed in the StyleViewer window and on the server after the raster is published.

To Reproduce

Go to the layer styling panel in QGIS.
Click on the raster layer you intend to publish.
Set the raster style to "Interpolation: Discrete."
Publish the layer to GeoServer using GeoCat Bridge.
Check the generated SLD file either in the StyleViewer or on the server.
See the incorrect <ColorMap> type in the SLD file.
Expected behavior
The SLD file should correctly use <ColorMap type="intervals"> when the raster style is set to "Interpolation: Discrete" to reflect the discrete intervals in the data. The <ColorMap type="ramp"> is inappropriate for this type of styling and should not be used.

Screenshots
![image](https://github.com/user-attachments/assets/55d5b1c1-787d-4307-a9fc-583fbf03dda9)
<img width="927" alt="image" src="https://github.com/user-attachments/assets/c921b48b-fe36-4bdb-baed-eefe086c39d8">

Should be:

<img width="913" alt="image" src="https://github.com/user-attachments/assets/88b5ed28-78e7-471f-a050-570066eb3c10">

Environment info (please complete the following information):

OS: macOS 14.6.1
QGIS version: LTR version of QGIS is 3.34.10.
Bridge version: GeoCat Bridge for QGIS 4.4.2 (based on bridgestyle 0.1.1)
Python version: [e.g., 3.9]

Additional context
Still van edit the SLD file manually on the server

**Comment by GeoSander** [comment]
Thanks for reporting this issue @dvandeijl.
I took the liberty to transfer this to the `bridge-style` repo, as that contains the code responsible for all SLD conversions out of QGIS Bridge.

May I conclude from the above that - simply put - you expect to see a `ColorMap` of type `intervals` (instead of `ramp`) in your SLD, when you have selected `Interpolation: Discrete` in QGIS?

Sander

**Comment by dvandeijl** [comment]
> Thanks for reporting this issue @dvandeijl. I took the liberty to transfer this to the `bridge-style` repo, as that contains the code responsible for all SLD conversions out of QGIS Bridge.
> 
> May I conclude from the above that - simply put - you expect to see a `ColorMap` of type `intervals` (instead of `ramp`) in your SLD, when you have selected `Interpolation: Discrete` in QGIS?
> 
> Sander

Yes that is correct

**Comment by GeoSander** [comment]
Alright, that's clear.

Interestingly, it seems as if this should just work: https://github.com/GeoCat/bridge-style/blob/master/bridgestyle/qgis/togeostyler.py#L201C1-L208C35
However, it seems that there was an API change in QGIS 3.38: https://qgis.org/pyqgis/master/core/Qgis.html#qgis.core.Qgis.ShaderInterpolationMethod

But you are on 3.34, so I'm not sure what's happening here.
Let me investigate.

**Comment by dvandeijl** [comment]
> Alright, that's clear.
> 
> Interestingly, it seems as if this should just work: https://github.com/GeoCat/bridge-style/blob/master/bridgestyle/qgis/togeostyler.py#L201C1-L208C35 However, it seems that there was an API change in QGIS 3.38: https://qgis.org/pyqgis/master/core/Qgis.html#qgis.core.Qgis.ShaderInterpolationMethod
> 
> But you are on 3.34, so I'm not sure what's happening here. Let me investigate.

The option exact also result in type=' ramp'

**Comment by GeoSander** [comment]
Right, so whatever `shader.colorRampType` is now (did not look yet), it apparently no longer matches `QgsColorRampShader.Exact` or `QgsColorRampShader.Discrete`, although those types _do_ still exist in 3.34 (otherwise you would have had a `NameError` or an `AttributeError`).
Now I understand why some people hate weakly typed languages (like Python)... 😉

**Comment by GeoSander** [comment]
Fixed and released in [GeoCat Bridge 4.5.0](https://plugins.qgis.org/plugins/geocatbridge/version/4.5.0/).
