### ISSUE TITLE
wrong xsd reference in style preview window

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/bridge-style#99]
**Describe the bug**

the reference to the sld xsd is incorrect in the style preview window, currently: StyledLayerDescriptor.xsd should be: http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd

![image](https://github.com/user-attachments/assets/70c5f8ac-e991-46a5-8665-b0d586516a74)

**Comment by GeoSander** [comment]
Fixed and released as part of [GeoCat Bridge 4.5.0](https://plugins.qgis.org/plugins/geocatbridge/version/4.5.0/) for QGIS.
